
export const allCategoryConstant = {
    ALL_CATEGORY_REQUEST : 'ALL_CATEGORY_REQUEST',
    ALL_CATEGORY_SUCCESS : 'ALL_CATEGORY_SUCCESS',
    ALL_CATEGORY_FAILUAR : 'ALL_CATEGORY_FAILUAR',
    ADD_CATEGORY_ITEM_REQUEST : 'ADD_CATEGORY_ITEM_REQUEST',
    ADD_CATEGORY_ITEM_SUCCESS : 'ADD_CATEGORY_ITEM_SUCCESS',
    ADD_CATEGORY_ITEM_FAILUAR : 'ADD_CATEGORY_ITEM_FAILUAR',
}


export const getProductPageConstant = {
    GET_PRODUCT_BY_SLUG_REQUEST : "GET_PRODUCT_BY_SLUG_REQUEST",
    GET_PRODUCT_BY_SLUG_SUCCESS : "GET_PRODUCT_BY_SLUG_SUCCESS",
    GET_PRODUCT_BY_SLUG_FAILUAR : "GET_PRODUCT_BY_SLUG_FAILUAR",
}
