export const authConstant ={
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILUAR : 'LOGIN_FAILUAR',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILUAR : 'LOGOUT_FAILUAR',

}

export const userDataConstant ={
    USER_SIGNUP_REQUEST : 'USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS : 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILUAR : 'USER_SIGNUP_FAILUAR',
}

export const productConstant = {
    GET_ALL_PRODUCT_REQUEST : "GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_SUCCESS : "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAILUAR : "GET_ALL_PRODUCT_FAILUAR",
}

export const allCategoryConstant = {
    ALL_CATEGORY_REQUEST : 'ALL_CATEGORY_REQUEST',
    ALL_CATEGORY_SUCCESS : 'ALL_CATEGORY_SUCCESS',
    ALL_CATEGORY_FAILUAR : 'ALL_CATEGORY_FAILUAR',
    ADD_CATEGORY_ITEM_REQUEST : 'ADD_CATEGORY_ITEM_REQUEST',
    ADD_CATEGORY_ITEM_SUCCESS : 'ADD_CATEGORY_ITEM_SUCCESS',
    ADD_CATEGORY_ITEM_FAILUAR : 'ADD_CATEGORY_ITEM_FAILUAR',
    UPDATE_CATEGOTY_REQUEST: 'UPDATE_CATEGOTY_REQUEST',
    UPDATE_CATEGOTY_SUCCESS: 'UPDATE_CATEGOTY_SUCCESS',
    UPDATE_CATEGOTY_FAILUAR: 'UPDATE_CATEGOTY_FAILUAR',
    UPDATE_CATEGOTY_FAILUAR: 'UPDATE_CATEGOTY_FAILUAR',
}




export const addProductConatat ={
    ADD_PRODUCT_REQUEST : 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILUAR : 'ADD_PRODUCT_FAILUAR',
}